<?php
extract($this->data);
//print('<pre>');print_r($approval_listing);exit;
?>

<head>
    <link rel="stylesheet" href="<?php echo $this->baseUrl('/') ?>assets/alertify/themes/alertify.core.css" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl('/') ?>assets/alertify/themes/alertify.default.css" id="toggleCSS" />
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:300,300i,400,400i,700" rel="stylesheet">
    <!--<link href="<?php echo $this->baseUrl('/') ?>assets/css/adminstyle.css" rel="stylesheet" type="text/css">-->
    <link href="<?php echo $this->baseUrl('/') ?>assets/css/bootstrap.css" rel="stylesheet" type="text/css">
    <link href="<?php echo $this->baseUrl('/') ?>assets/css/bootstrap-table.min.css" rel="stylesheet" type="text/css">
    <link href="<?php echo $this->baseUrl('/') ?>assets/css/ionicons.min.css" rel="stylesheet" type="text/css">
    <link href="<?php echo $this->baseUrl('/') ?>assets/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!--<link href="<?php echo $this->baseUrl('/') ?>assets/css/main.css" rel="stylesheet" type="text/css">-->
    <link href="<?php echo $this->baseUrl('/') ?>assets/css/jquery-ui.css" rel="stylesheet" type="text/css">
    <link href="<?php echo $this->baseUrl('/') ?>assets/css/custom.css" rel="stylesheet" type="text/css">
    <style>
        .form-control{
            text-align: center;
        }
        .select2{
            text-align: center;
        }
    </style>
    <title>BYGO - Areas</title>
</head>


<div class="container">
    <div class="row">
        <br>     
        <div class="wrapper">	
            <div class="container-fluid primary-content">
                <div class="primary-content-heading clearfix">
                    <ul class="breadcrumb pull-left">
                        <li><i class="fa fa-home"></i><a href="/Admin/Approval">&nbsp;Approvals</a></li>
                        <li><b>Areas</b></li>
                    </ul>
                    <div class="pull-right">
                        <a href="/Admin/Area/newarea"><button type="button" class="btn btn-success"><i class="fa fa-plus-circle"></i> New Area</button></a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="widget-header">
                            <h3 class="center"><b>Bygo Areas</b></h3>
                        </div>

                        <div class="table-responsive">
                            <table id="area_table" class="table table-bordred table-striped dataTable">

                                <thead>

                                <th width="5%">Id</th>
                                <th width="20%">Name</th>
                                <th width="20%">Town</th>
                                <th width="20%">District</th>
                                <th width="15%">State</th>
                                <th width="15%">Status</th>
                                <th width="5%">Options</th>
                                </thead>
                                <tbody>
                                    <?php if (count($area_listing) > 0) {
                                        foreach ($area_listing as $val) {
                                            ?>
                                            <tr>
                                                <td><?php echo $val['id']; ?></td>
                                                <td><?php echo ucwords($val['name']); ?></td>
                                                <td><?php echo $val['town']; ?></td>
                                                <td><?php echo $val['district']; ?></td>
                                                <td><?php echo $val['state']; ?></td>
                                                <td>
        <?php if ($val['status'] == '1') {
            $status = 'Active';
            $class = 'btn-primary';
        } else {
            $status = 'Inactive';
            $class = 'btn-warning';
        } ?>
                                                    <input type="button" id="area_<?php echo $val['id'] ?>" class="<?php echo $class; ?>" onclick="changestatus('<?php echo $val['id'] ?>','<?php echo $val['status'] ?>','<?php echo ucwords($val['name']); ?>');" value="<?php echo $status; ?>"/>
                                                </td>
                                                <td><a title="<?php echo "Edit "; ?>" href="<?php echo $this->url(array('module' => 'Admin', 'controller' => 'Area', 'action' => 'editarea', 'id' => $val['id']), null, true); ?>" class="btn btn-xs btn-default fa fa-edit"></a>&nbsp;&nbsp;&nbsp;</td>
                                            </tr>
    <?php }
} else { ?>
                                        <tr>
                                            <td colspan="12">No records found</td>
                                        </tr>
<?php } ?>
                                </tbody>

                            </table>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<link rel="stylesheet" href="<?php echo $this->baseUrl('/') ?>assets/css/jquery-ui.css"> 
<script src="<?php echo $this->baseUrl('/') ?>assets/jquery/jquery-1.10.2.js"></script>

<script src="<?php echo $this->baseUrl('/') ?>assets/jquery/jquery-2.1.0.min.js"></script>
<script src="<?php echo $this->baseUrl('/') ?>assets/jquery-ui/jquery-ui-1.10.4.custom.min.js"></script>
<script src="<?php echo $this->baseUrl('/') ?>assets/bootstrap/bootstrap.js"></script>
<script src="<?php echo $this->baseUrl('/') ?>assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<script src="<?php echo $this->baseUrl('/') ?>assets/plugins/select2/select2.min.js"></script>
<script src="<?php echo $this->baseUrl('/') ?>assets/plugins/bootstrap-tagsinput/bootstrap-tagsinput.min.js"></script>
<script src="<?php echo $this->baseUrl('/'); ?>assets/bootstrap/view-utilities.js" type="text/javascript"></script> 

<script src="<?php echo $this->baseUrl('/') ?>assets/alertify/lib/alertify.min.js"></script>
<script src="<?php echo $this->baseUrl('/') ?>assets/jquery-ui/jquery-ui-1.11.4.custom.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('/') ?>assets/DataTables/datatables.min.css"/>
<script type="text/javascript" src="<?php echo $this->baseUrl('/') ?>assets/DataTables/datatables.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
       $('#area_table').DataTable({
            "order": [[ 0, "desc" ]]
       });
    });
    

    function changestatus(id,status,name){
        alertify.confirm("Update "+name+" status?",
        function(e){
            if(e){
                $("#area_"+id).prop('disabled', true);
                $.ajax({
                    type: 'Post',
                    url: "/Admin/Area/changestatus", 
                    dataType: 'json',
                    data:{
                       id : id,
                       status : status
                    },    
                    success: function(response){
                        if(response.respo == 1){
                            alertify.success(name+" status changed successfully");
                            if(status == '1'){
                                $("#area_"+id).removeClass('btn-primary').addClass('btn-warning');
                                $('#area_'+id).val('');$('#area_'+id).val('Inactive');
                            }else{
                                $("#area_"+id).removeClass('btn-warning').addClass('btn-primary');
                                $('#area_'+id).val('');$('#area_'+id).val('Active');
                            }
                        }else{
                            alertify.error(response.msg);
                        }
                    }
                });
            }else{
                return;
            }
        });
    }
</script>
